"""Builds a FITS file for submission to AAVSO's AVSpec spectroscopic
database (https://www.aavso.org/apps/avspec/submit), from this app's own
final calibrated (wavelength, flux) result -- spectro/reduction.py's
output, see ReductionPanel.get_final_spectrum().

Header keywords here were compiled from AAVSO's own "Quick Guide to
Submit Spectroscopic Data into AVSpec" (v2.1, Sept 2022) and publicly
documented BSS/BeSS-format keyword references -- OBJECT/OBSERVER/DATE-OBS
and the CRVAL1/CDELT1/CRPIX1/CTYPE1/CUNIT1 wavelength-axis keywords are
standard FITS and were directly confirmed; BSS_SITE/BSS_INST/BSS_LAT/
BSS_LONG/BSS_ELEV were confirmed against AAVSO forum posts and BeSS
documentation excerpts. AAVSO's full "technical guide" (linked from the
quick guide, hosted at basebe.obspm.fr) was NOT reachable while building
this -- this covers the fields verified from what WAS reachable, not
necessarily AAVSO's complete keyword list. AVSpec runs its own automatic
header validation on upload and reports exactly what's missing/wrong (see
the quick guide's own step 5-6) -- treat that as the authoritative check,
not this module.
"""

from __future__ import annotations

from datetime import datetime, timezone

import numpy as np
from astropy.io import fits


class AvspecExportError(RuntimeError):
    pass


def build_avspec_hdu(
    wl: np.ndarray, flux: np.ndarray, *, object_name: str, observer_code: str, site_name: str,
    site_lat_deg: float, site_lon_deg: float, site_elevation_m: float, instrument_name: str,
    observation_time: datetime | None = None,
) -> fits.PrimaryHDU:
    """Builds the FITS HDU -- does not write to disk, see write_avspec_fits.
    Raises AvspecExportError if the wavelength axis isn't evenly spaced
    (CRVAL1/CDELT1 is a LINEAR axis descriptor -- it can't represent an
    uneven grid, and silently writing one anyway would just be wrong
    data). spectro.reduction.apply_response always produces an evenly
    spaced wl array (constant dispersion fit to real pixels), so this
    should never actually trip for spectra produced by this app's own
    pipeline -- it's here in case that assumption ever changes."""
    if len(wl) < 2:
        raise AvspecExportError("spectrum has fewer than 2 points -- nothing to export")
    steps = np.diff(wl)
    if not np.allclose(steps, steps[0], rtol=1e-3):
        raise AvspecExportError("wavelength axis isn't evenly spaced -- can't express it as a linear CRVAL1/CDELT1 axis")

    when = observation_time if observation_time is not None else datetime.now(timezone.utc)

    hdu = fits.PrimaryHDU(data=flux.astype(np.float64))
    header = hdu.header
    header["OBJECT"] = (object_name, "Target star")
    header["OBSERVER"] = (observer_code, "AAVSO observer code (Obscode)")
    header["DATE-OBS"] = (when.strftime("%Y-%m-%dT%H:%M:%S"), "UTC observation time")
    header["TELESCOP"] = (instrument_name, "Instrument name, as registered with AAVSO")
    header["BSS_INST"] = (instrument_name, "Instrument name, as registered with AAVSO")
    header["BSS_SITE"] = (site_name, "Site name, as registered with AAVSO")
    header["BSS_LAT"] = (site_lat_deg, "Site latitude, degrees")
    header["BSS_LONG"] = (site_lon_deg, "Site longitude, degrees")
    header["BSS_ELEV"] = (site_elevation_m, "Site elevation, meters")
    header["CRPIX1"] = (1, "Reference pixel (1-indexed)")
    header["CRVAL1"] = (float(wl[0]), "Wavelength at CRPIX1, Angstrom")
    header["CDELT1"] = (float(steps[0]), "Wavelength step, Angstrom/pixel")
    header["CTYPE1"] = ("LINEAR", "Linear wavelength axis")
    header["CUNIT1"] = ("Angstrom", "Wavelength unit")
    header["BUNIT"] = ("Relative flux", "Response-corrected, NOT flux-calibrated to physical units")
    header.add_history("Generated by spectro_gui.py (spectro/avspec_export.py) -- verify headers against AAVSO's own AVSpec technical guide before submitting.")
    return hdu


def write_avspec_fits(path: str, wl: np.ndarray, flux: np.ndarray, **kwargs) -> None:
    hdu = build_avspec_hdu(wl, flux, **kwargs)
    hdu.writeto(path, overwrite=True)
