"""Real reduction pipeline: frame stacking, dark/flat calibration,
wavelength calibration via detected reference lines, and instrument-
response flux calibration -- pure functions operating on 2D numpy frames,
no Tk.

Shares the same trail/pixel geometry the live-preview mock in
gui/panels.py uses to synthesize frames (TRAIL_ROW etc. below) -- single
source of truth, so a frame generated by the mock and a frame processed
by this module can never silently disagree on where the trail or the
reference lines actually sit. gui/panels.py imports these names rather
than redefining them.

This module is the "go all the way" half of the mockup: everything here
is real math that would work unchanged on real captured frames, applied
to synthetic-but-realistic frames because no camera is connected yet
(see gui/panels.py's own module docstring for what's still purely a
visual mock).
"""

from __future__ import annotations

import numpy as np

from spectro.catalog import REFERENCE_LINES

# Layout constants -- shared with spectro/gui/panels.py's synthetic frame
# generator (_synthetic_trail_image), which paints its trail at exactly
# these pixel/wavelength coordinates.
TRAIL_ROW = 45
TRAIL_START_PX = 70
TRAIL_END_PX = 420
PROFILE_HALF_HEIGHT = 6
ASSUMED_WL_MIN, ASSUMED_WL_MAX = 3800.0, 7200.0


class ReductionError(RuntimeError):
    pass


def px_for_wavelength(wl: float) -> float:
    """Where a real line WOULD land on the trail under the assumed linear
    dispersion -- the starting guess later refined by fit_dispersion once
    real lines have actually been detected."""
    frac = (wl - ASSUMED_WL_MIN) / (ASSUMED_WL_MAX - ASSUMED_WL_MIN)
    return TRAIL_START_PX + frac * (TRAIL_END_PX - TRAIL_START_PX)


def wavelength_for_px(px: np.ndarray) -> np.ndarray:
    """Inverse of px_for_wavelength."""
    frac = (px - TRAIL_START_PX) / (TRAIL_END_PX - TRAIL_START_PX)
    return ASSUMED_WL_MIN + frac * (ASSUMED_WL_MAX - ASSUMED_WL_MIN)


def extract_profile(image: np.ndarray, trail_row: int = TRAIL_ROW, half_height: int = PROFILE_HALF_HEIGHT) -> np.ndarray:
    """Column-sum across a band around the trail row -- collapses the 2D
    trail into a 1D profile, the same crude step a real reduction
    pipeline does."""
    y0 = max(0, trail_row - half_height)
    y1 = min(image.shape[0], trail_row + half_height + 1)
    return image[y0:y1, :].sum(axis=0)


def stack_frames(frames: list[np.ndarray]) -> np.ndarray | None:
    """Mean-stack a list of same-shaped frames -- real signal adds
    coherently while independent per-frame noise averages down by
    sqrt(N), which is the entire reason multi-frame capture (see
    AcquisitionPanel's "Frames to stack" control) is worth doing over a
    single exposure. None if given no frames."""
    if not frames:
        return None
    return np.mean(np.stack(frames, axis=0), axis=0)


def snr_gain(n_frames: int) -> float:
    """How much better the SNR of an N-frame stack is vs. a single frame,
    assuming independent per-frame noise -- sqrt(N), the standard result
    used to justify why "frames to stack" > 1 is worth doing."""
    return float(np.sqrt(max(n_frames, 1)))


def calibrate_science(
    science_stack: np.ndarray, dark_stack: np.ndarray, flat_stack: np.ndarray,
    offset_stack: np.ndarray | None = None,
) -> np.ndarray:
    """(science - dark) / normalized_flat -- the standard basic CCD
    reduction formula. If offset/bias frames are given, the flat is
    itself bias-corrected first (flat - offset): physically the flat
    needs its OWN bias frame at the flat's own exposure, approximated
    here from the star's offset frames since bias level depends mostly on
    gain (usually shared) rather than exposure -- a documented
    simplification, not a real per-setup flat-bias capture."""
    flat = flat_stack - offset_stack if offset_stack is not None else flat_stack
    flat_mean = float(flat.mean())
    if flat_mean <= 0:
        raise ReductionError("flat field averages to zero or negative -- can't normalize")
    flat_norm = np.clip(flat / flat_mean, 0.05, None)  # guard against near-zero columns blowing up the division
    return (science_stack - dark_stack) / flat_norm


def detect_line_pixels(
    profile: np.ndarray, expected_lines: list[tuple[str, float]] = REFERENCE_LINES, search_half_width: int = 15,
) -> list[tuple[str, float, int]]:
    """For each known REFERENCE_LINES entry, looks for a local minimum
    (absorption dip) within search_half_width pixels of where it's
    ASSUMED to sit (px_for_wavelength) -- a real, if simple, line-
    centroiding step, not just trusting the assumed linear dispersion.
    Returns (label, known_wl, detected_px) only for lines where a clear
    INTERIOR minimum was found -- skips lines whose search window runs
    off the trail, or where the minimum sits right at the window edge
    (more likely noise/continuum slope than a real dip)."""
    detected = []
    n = len(profile)
    for label, wl in expected_lines:
        center_px = px_for_wavelength(wl)
        lo = int(round(center_px - search_half_width))
        hi = int(round(center_px + search_half_width))
        if lo < TRAIL_START_PX or hi >= min(n, TRAIL_END_PX):
            continue
        window = profile[lo:hi + 1]
        local_min_idx = int(np.argmin(window))
        if local_min_idx in (0, len(window) - 1):
            continue  # minimum at the window edge -- not a real interior dip
        detected.append((label, wl, lo + local_min_idx))
    return detected


def fit_dispersion(detected: list[tuple[str, float, int]]) -> tuple[float, float] | None:
    """Linear pixel->wavelength fit (wl = a*px + b) from real detected
    line positions -- needs at least 2 lines. Returns (a, b) or None."""
    if len(detected) < 2:
        return None
    pixels = np.array([px for _, _, px in detected], dtype=float)
    wavelengths = np.array([wl for _, wl, _ in detected], dtype=float)
    a, b = np.polyfit(pixels, wavelengths, 1)
    return float(a), float(b)


def pixel_wavelength_array(pixels: np.ndarray, dispersion: tuple[float, float] | None = None) -> np.ndarray:
    """Pixel->wavelength mapping using a REAL fitted dispersion if given
    (see fit_dispersion), else falling back to the assumed linear one."""
    if dispersion is None:
        return wavelength_for_px(pixels)
    a, b = dispersion
    return a * pixels + b


def resolution_at(wl: float, dispersion_a: float, fwhm_px: float = 8.0) -> float:
    """R = lambda / delta_lambda, delta_lambda estimated from a typical
    line FWHM in pixels (~8px, matching the Balmer line widths used
    elsewhere in this app's mock, see gui/panels.py's _LINE_WIDTH_A) --
    an estimate, not a measured line-fit width, but fed by the REAL
    fitted dispersion rather than a hardcoded number."""
    delta_lambda = abs(dispersion_a) * fwhm_px
    if delta_lambda <= 0:
        return float("nan")
    return wl / delta_lambda


def compute_response(
    reference_calibrated_image: np.ndarray, reference_wl: np.ndarray, reference_flux: np.ndarray,
    dispersion: tuple[float, float] | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Instrument response = measured counts / known relative flux, at
    each pixel across the trail -- the correction that, divided out of a
    target's own measured counts (see apply_response), removes the
    instrument's own wavelength-dependent sensitivity. Returns (pixels,
    wavelengths, response, measured_profile)."""
    profile = extract_profile(reference_calibrated_image)
    pixels = np.arange(TRAIL_START_PX, TRAIL_END_PX)
    measured = profile[TRAIL_START_PX:TRAIL_END_PX].astype(float)
    wavelengths = pixel_wavelength_array(pixels, dispersion)
    known = np.interp(wavelengths, reference_wl, reference_flux, left=np.nan, right=np.nan)
    known = np.clip(known, 1e-3, None)
    response = measured / known
    return pixels, wavelengths, response, measured


def apply_response(
    target_calibrated_image: np.ndarray, response: np.ndarray, dispersion: tuple[float, float] | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Divides the target's own measured profile by the reference-derived
    response, over the SAME pixel range compute_response used -- the
    actual flux-calibration step. Returns (wavelengths, flux) normalized
    to a max of 1 for display (still a RELATIVE flux calibration, not
    absolute physical units -- no absolute photometric standard is used
    anywhere in this app)."""
    profile = extract_profile(target_calibrated_image)
    pixels = np.arange(TRAIL_START_PX, TRAIL_END_PX)
    measured = profile[TRAIL_START_PX:TRAIL_END_PX].astype(float)
    wavelengths = pixel_wavelength_array(pixels, dispersion)
    response_safe = np.where(np.abs(response) < 1e-6, np.nan, response)
    flux = measured / response_safe
    valid = np.isfinite(flux)
    if valid.any() and np.nanmax(flux[valid]) > 0:
        flux = flux / np.nanmax(flux[valid])
    return wavelengths, flux
