import math
from datetime import datetime, timezone

import numpy as np
import pytest

from am5.angles import angular_separation_deg, equatorial_to_altaz
from am5.polar_alignment import fit_rotation_axis, polar_alignment_error


def _unit_vector(ra_deg: float, dec_deg: float) -> np.ndarray:
    ra, dec = math.radians(ra_deg), math.radians(dec_deg)
    return np.array([math.cos(dec) * math.cos(ra), math.cos(dec) * math.sin(ra), math.sin(dec)])


def _to_radec(v: np.ndarray) -> tuple[float, float]:
    v = v / np.linalg.norm(v)
    dec_deg = math.degrees(math.asin(max(-1.0, min(1.0, v[2]))))
    ra_deg = math.degrees(math.atan2(v[1], v[0])) % 360.0
    return ra_deg, dec_deg


def _rotation_matrix(axis: np.ndarray, angle_deg: float) -> np.ndarray:
    axis = axis / np.linalg.norm(axis)
    theta = math.radians(angle_deg)
    k = np.array([[0, -axis[2], axis[1]], [axis[2], 0, -axis[0]], [-axis[1], axis[0], 0]])
    return np.eye(3) + math.sin(theta) * k + (1 - math.cos(theta)) * (k @ k)


def test_fit_rotation_axis_recovers_a_known_axis():
    # 3 points on a circle of radius 5 deg around a known, deliberately
    # off-true-pole axis -- generated by rotating the trivial "circle
    # around the true celestial pole" case by a known rotation, so the
    # test doesn't need to hand-derive spherical trig for an arbitrary
    # axis, just exercise the fit's rotational invariance.
    true_axis_ra, true_axis_dec = 47.0, 88.0
    pole = np.array([0.0, 0.0, 1.0])
    target = _unit_vector(true_axis_ra, true_axis_dec)
    rot_axis = np.cross(pole, target)
    rot_angle_deg = math.degrees(math.acos(np.clip(np.dot(pole, target), -1.0, 1.0)))
    r = _rotation_matrix(rot_axis, rot_angle_deg) if np.linalg.norm(rot_axis) > 1e-9 else np.eye(3)

    points = []
    for phase_deg in (0.0, 120.0, 240.0):
        v = _unit_vector(phase_deg, 85.0)  # 5 deg from the true pole, pre-rotation
        points.append(_to_radec(r @ v))

    fitted_ra, fitted_dec = fit_rotation_axis(points)
    assert angular_separation_deg(fitted_ra, fitted_dec, true_axis_ra, true_axis_dec) < 0.01


def test_fit_rotation_axis_exact_pole_case_needs_no_rotation_helper():
    # Simplest possible case, independent of the rotation-matrix machinery
    # the test above relies on: 3 points on a circle centered exactly on
    # the true celestial pole.
    points = [_to_radec(_unit_vector(phase, 85.0)) for phase in (0.0, 120.0, 240.0)]
    fitted_ra, fitted_dec = fit_rotation_axis(points)
    assert fitted_dec == pytest.approx(90.0, abs=1e-6)


def test_fit_rotation_axis_requires_exactly_three_points():
    with pytest.raises(ValueError):
        fit_rotation_axis([(0.0, 80.0), (10.0, 80.0)])
    with pytest.raises(ValueError):
        fit_rotation_axis([(0.0, 80.0), (10.0, 80.0), (20.0, 80.0), (30.0, 80.0)])


def test_fit_rotation_axis_rejects_degenerate_points():
    with pytest.raises(ValueError):
        fit_rotation_axis([(10.0, 80.0), (10.0, 80.0), (10.0, 80.0)])


def test_polar_alignment_error_zero_when_axis_is_the_true_pole():
    when = datetime(2026, 6, 15, 3, 0, 0, tzinfo=timezone.utc)
    lat_deg, lon_deg = 46.18, 6.14
    result = polar_alignment_error(123.4, 90.0, lat_deg, lon_deg, when)  # RA is irrelevant exactly at DEC=90
    assert result.error_deg < 1e-6
    assert abs(result.error_alt_deg) < 1e-6
    assert abs(result.error_az_deg) < 1e-6


def test_polar_alignment_error_matches_a_direct_altaz_conversion():
    when = datetime(2026, 3, 20, 12, 0, 0, tzinfo=timezone.utc)
    lat_deg, lon_deg = 46.18, 6.14
    axis_ra_deg, axis_dec_deg = 10.0, 89.5  # half a degree off the pole
    az_deg, alt_deg = equatorial_to_altaz(axis_ra_deg, axis_dec_deg, lat_deg, lon_deg, when)

    result = polar_alignment_error(axis_ra_deg, axis_dec_deg, lat_deg, lon_deg, when)

    assert result.axis_alt_deg == pytest.approx(alt_deg)
    assert result.axis_az_deg == pytest.approx(az_deg)
    assert result.error_alt_deg == pytest.approx(alt_deg - lat_deg)
    expected_az_error_deg = ((az_deg - 0.0 + 180.0) % 360.0) - 180.0
    assert result.error_az_deg == pytest.approx(expected_az_error_deg)
    assert result.error_deg > 0.0
