import math
from datetime import datetime, timezone

import numpy as np
import pytest
from astropy.wcs import WCS

from am5.angles import angular_separation_deg, equatorial_to_altaz
from am5.polar_alignment import (
    axis_radec_from_frame_shift,
    correction_triangle_radec,
    fit_rotation_axis,
    offset_radec_by_east_north,
    polar_alignment_error,
    project_radec_to_pixel,
    tangent_plane_offset_arcsec,
    true_pole_radec,
)


def _unit_vector(ra_deg: float, dec_deg: float) -> np.ndarray:
    ra, dec = math.radians(ra_deg), math.radians(dec_deg)
    return np.array([math.cos(dec) * math.cos(ra), math.cos(dec) * math.sin(ra), math.sin(dec)])


def _to_radec(v: np.ndarray) -> tuple[float, float]:
    v = v / np.linalg.norm(v)
    dec_deg = math.degrees(math.asin(max(-1.0, min(1.0, v[2]))))
    ra_deg = math.degrees(math.atan2(v[1], v[0])) % 360.0
    return ra_deg, dec_deg


def _rotation_matrix(axis: np.ndarray, angle_deg: float) -> np.ndarray:
    axis = axis / np.linalg.norm(axis)
    theta = math.radians(angle_deg)
    k = np.array([[0, -axis[2], axis[1]], [axis[2], 0, -axis[0]], [-axis[1], axis[0], 0]])
    return np.eye(3) + math.sin(theta) * k + (1 - math.cos(theta)) * (k @ k)


def test_fit_rotation_axis_recovers_a_known_axis():
    # 3 points on a circle of radius 5 deg around a known, deliberately
    # off-true-pole axis -- generated by rotating the trivial "circle
    # around the true celestial pole" case by a known rotation, so the
    # test doesn't need to hand-derive spherical trig for an arbitrary
    # axis, just exercise the fit's rotational invariance.
    true_axis_ra, true_axis_dec = 47.0, 88.0
    pole = np.array([0.0, 0.0, 1.0])
    target = _unit_vector(true_axis_ra, true_axis_dec)
    rot_axis = np.cross(pole, target)
    rot_angle_deg = math.degrees(math.acos(np.clip(np.dot(pole, target), -1.0, 1.0)))
    r = _rotation_matrix(rot_axis, rot_angle_deg) if np.linalg.norm(rot_axis) > 1e-9 else np.eye(3)

    points = []
    for phase_deg in (0.0, 120.0, 240.0):
        v = _unit_vector(phase_deg, 85.0)  # 5 deg from the true pole, pre-rotation
        points.append(_to_radec(r @ v))

    fitted_ra, fitted_dec = fit_rotation_axis(points)
    assert angular_separation_deg(fitted_ra, fitted_dec, true_axis_ra, true_axis_dec) < 0.01


def test_fit_rotation_axis_exact_pole_case_needs_no_rotation_helper():
    # Simplest possible case, independent of the rotation-matrix machinery
    # the test above relies on: 3 points on a circle centered exactly on
    # the true celestial pole.
    points = [_to_radec(_unit_vector(phase, 85.0)) for phase in (0.0, 120.0, 240.0)]
    fitted_ra, fitted_dec = fit_rotation_axis(points)
    assert fitted_dec == pytest.approx(90.0, abs=1e-6)


def test_fit_rotation_axis_requires_exactly_three_points():
    with pytest.raises(ValueError):
        fit_rotation_axis([(0.0, 80.0), (10.0, 80.0)])
    with pytest.raises(ValueError):
        fit_rotation_axis([(0.0, 80.0), (10.0, 80.0), (20.0, 80.0), (30.0, 80.0)])


def test_fit_rotation_axis_rejects_degenerate_points():
    with pytest.raises(ValueError):
        fit_rotation_axis([(10.0, 80.0), (10.0, 80.0), (10.0, 80.0)])


def test_polar_alignment_error_zero_when_axis_is_the_true_pole():
    when = datetime(2026, 6, 15, 3, 0, 0, tzinfo=timezone.utc)
    lat_deg, lon_deg = 46.18, 6.14
    result = polar_alignment_error(123.4, 90.0, lat_deg, lon_deg, when)  # RA is irrelevant exactly at DEC=90
    assert result.error_deg < 1e-6
    assert abs(result.error_alt_deg) < 1e-6
    assert abs(result.error_az_deg) < 1e-6


def test_polar_alignment_error_matches_a_direct_altaz_conversion():
    when = datetime(2026, 3, 20, 12, 0, 0, tzinfo=timezone.utc)
    lat_deg, lon_deg = 46.18, 6.14
    axis_ra_deg, axis_dec_deg = 10.0, 89.5  # half a degree off the pole
    az_deg, alt_deg = equatorial_to_altaz(axis_ra_deg, axis_dec_deg, lat_deg, lon_deg, when)

    result = polar_alignment_error(axis_ra_deg, axis_dec_deg, lat_deg, lon_deg, when)

    assert result.axis_alt_deg == pytest.approx(alt_deg)
    assert result.axis_az_deg == pytest.approx(az_deg)
    assert result.error_alt_deg == pytest.approx(alt_deg - lat_deg)
    expected_az_error_deg = ((az_deg - 0.0 + 180.0) % 360.0) - 180.0
    assert result.error_az_deg == pytest.approx(expected_az_error_deg)
    assert result.error_deg > 0.0


def test_true_pole_radec_gives_plus_90_north_minus_90_south():
    assert true_pole_radec(46.18) == (0.0, 90.0)
    assert true_pole_radec(-33.0) == (0.0, -90.0)


def _wcs_matching_this_projects_own_pixel_convention(crval1, crval2, pixel_scale_deg, rotation_deg) -> WCS:
    # A CD matrix constructed to match THIS project's own pixel layout
    # (column increases east, row increases south -- see
    # camera/mock_camera.py's _render_stars) at rotation_deg=0, then
    # generalized to a nonzero rotation the same way a real solver would
    # report one, with rotation_deg extracted via atan2(CD1_2, CD1_1) --
    # exactly matching camera/platesolve.py's own extraction convention.
    # Ground truth for project_radec_to_pixel: independent of this
    # project's own projection code, using astropy.wcs's authoritative
    # TAN-projection math instead.
    w = WCS(naxis=2)
    w.wcs.crpix = [1000.5, 500.5]  # arbitrary reference pixel, deliberately not the frame centre
    w.wcs.crval = [crval1, crval2]
    w.wcs.ctype = ["RA---TAN", "DEC--TAN"]
    rot = math.radians(rotation_deg)
    s = pixel_scale_deg
    w.wcs.cd = [[s * math.cos(rot), s * math.sin(rot)], [s * math.sin(rot), -s * math.cos(rot)]]
    return w


def _wcs_with_flipped_parity(crval1, crval2, pixel_scale_deg, rotation_deg) -> WCS:
    # Same construction as _wcs_matching_this_projects_own_pixel_
    # convention, but with the second CD row negated -- flips the
    # matrix's determinant sign (always negative above; always positive
    # here), matching a real optical path mirrored relative to this
    # project's originally-assumed convention. Confirmed this is the
    # real-world case for this project's actual finder camera (see
    # project_radec_to_pixel's own flip_parity docstring: its real solved
    # WCS has det(CD) ~= +2.18e-7, not negative).
    w = WCS(naxis=2)
    w.wcs.crpix = [1000.5, 500.5]
    w.wcs.crval = [crval1, crval2]
    w.wcs.ctype = ["RA---TAN", "DEC--TAN"]
    rot = math.radians(rotation_deg)
    s = pixel_scale_deg
    w.wcs.cd = [[s * math.cos(rot), s * math.sin(rot)], [-s * math.sin(rot), s * math.cos(rot)]]
    return w


@pytest.mark.parametrize("rotation_deg", [0.0, 15.0, 90.0, -45.0, 180.0, 178.0])
def test_project_radec_to_pixel_matches_astropy_wcs_for_a_flipped_parity(rotation_deg):
    # Regression, found on real hardware: project_radec_to_pixel used to
    # assume a single fixed parity (matching
    # _wcs_matching_this_projects_own_pixel_convention's always-negative
    # determinant) -- our actual finder camera's real solved WCS has the
    # OPPOSITE parity (positive determinant), confirmed by computing
    # det(CD) from a real solve-field .wcs file produced during live PAA
    # testing. With the wrong parity assumed, the polar-alignment
    # overlay's correction arrows pointed a direction that didn't match
    # reality when the operator tried to physically follow them -- worse
    # than not drawing an arrow at all. flip_parity=True negates
    # north_arcsec before the otherwise-unchanged formula; verified here
    # against astropy.wcs's own authoritative TAN-projection math for a
    # determinant-flipped CD matrix, at multiple rotations (not just the
    # trivial rot=0 case, which coincidentally can't distinguish a sign
    # bug in the rotation-dependent cross terms).
    pixel_scale_arcsec = 1.72
    center_ra_deg, center_dec_deg = 30.0, 60.0
    w = _wcs_with_flipped_parity(center_ra_deg, center_dec_deg, pixel_scale_arcsec / 3600.0, rotation_deg)
    crpix_x, crpix_y = w.wcs.crpix
    cd11, cd12 = w.wcs.cd[0]
    cd21, cd22 = w.wcs.cd[1]
    assert (cd11 * cd22 - cd12 * cd21) > 0.0  # sanity: this fixture really is the flipped-parity case
    extracted_rotation_deg = math.degrees(math.atan2(cd12, cd11))
    extracted_scale_arcsec = math.sqrt(cd11 ** 2 + cd21 ** 2) * 3600.0

    test_ra_deg, test_dec_deg = center_ra_deg + 0.002, center_dec_deg + 0.001
    px, py = w.all_world2pix([[test_ra_deg, test_dec_deg]], 1)[0]
    expected_delta_col, expected_delta_row = px - crpix_x, py - crpix_y

    delta_col, delta_row = project_radec_to_pixel(
        test_ra_deg, test_dec_deg, center_ra_deg, center_dec_deg, extracted_scale_arcsec, extracted_rotation_deg,
        flip_parity=True,
    )
    assert delta_col == pytest.approx(expected_delta_col, abs=0.01)
    assert delta_row == pytest.approx(expected_delta_row, abs=0.01)

    # And confirm flip_parity actually matters -- the non-flipped call
    # must NOT match this fixture's expected offsets (except in
    # degenerate cases), otherwise the parameter would be a no-op.
    wrong_col, wrong_row = project_radec_to_pixel(
        test_ra_deg, test_dec_deg, center_ra_deg, center_dec_deg, extracted_scale_arcsec, extracted_rotation_deg,
        flip_parity=False,
    )
    assert (wrong_col, wrong_row) != pytest.approx((expected_delta_col, expected_delta_row), abs=0.01)


@pytest.mark.parametrize("rotation_deg", [0.0, 15.0, 90.0, -45.0, 180.0])
def test_project_radec_to_pixel_matches_astropy_wcs_for_a_small_offset(rotation_deg):
    pixel_scale_arcsec = 1.72
    center_ra_deg, center_dec_deg = 30.0, 60.0
    w = _wcs_matching_this_projects_own_pixel_convention(center_ra_deg, center_dec_deg, pixel_scale_arcsec / 3600.0, rotation_deg)
    crpix_x, crpix_y = w.wcs.crpix
    cd11, cd12 = w.wcs.cd[0]
    extracted_rotation_deg = math.degrees(math.atan2(cd12, cd11))
    extracted_scale_arcsec = math.sqrt(cd11 ** 2 + w.wcs.cd[1][0] ** 2) * 3600.0

    test_ra_deg, test_dec_deg = center_ra_deg + 0.002, center_dec_deg + 0.001  # small -- exact within the linear (small-angle) regime
    px, py = w.all_world2pix([[test_ra_deg, test_dec_deg]], 1)[0]
    expected_delta_col, expected_delta_row = px - crpix_x, py - crpix_y

    delta_col, delta_row = project_radec_to_pixel(
        test_ra_deg, test_dec_deg, center_ra_deg, center_dec_deg, extracted_scale_arcsec, extracted_rotation_deg,
    )
    assert delta_col == pytest.approx(expected_delta_col, abs=0.01)
    assert delta_row == pytest.approx(expected_delta_row, abs=0.01)


def test_project_radec_to_pixel_matches_astropy_wcs_for_a_large_offset():
    # Half a degree offset -- big enough that the flat small-angle
    # approximation (circular_diff_deg-based) used elsewhere in this
    # project would visibly diverge from the true TAN projection; this
    # confirms project_radec_to_pixel doesn't have that limitation.
    pixel_scale_arcsec = 1.72
    center_ra_deg, center_dec_deg = 30.0, 89.3
    w = _wcs_matching_this_projects_own_pixel_convention(center_ra_deg, center_dec_deg, pixel_scale_arcsec / 3600.0, 20.0)
    crpix_x, crpix_y = w.wcs.crpix
    cd11, cd12 = w.wcs.cd[0]
    extracted_rotation_deg = math.degrees(math.atan2(cd12, cd11))
    extracted_scale_arcsec = math.sqrt(cd11 ** 2 + w.wcs.cd[1][0] ** 2) * 3600.0

    test_ra_deg, test_dec_deg = center_ra_deg + 0.5, center_dec_deg - 0.3
    px, py = w.all_world2pix([[test_ra_deg, test_dec_deg]], 1)[0]
    expected_delta_col, expected_delta_row = px - crpix_x, py - crpix_y

    delta_col, delta_row = project_radec_to_pixel(
        test_ra_deg, test_dec_deg, center_ra_deg, center_dec_deg, extracted_scale_arcsec, extracted_rotation_deg,
    )
    assert delta_col == pytest.approx(expected_delta_col, abs=0.5)
    assert delta_row == pytest.approx(expected_delta_row, abs=0.5)


def test_project_radec_to_pixel_is_ra_independent_exactly_at_the_pole():
    # The true celestial pole's RA is meaningless -- project_radec_to_pixel
    # must give the SAME pixel offset no matter which arbitrary RA
    # true_pole_radec (or a caller) happens to pass alongside dec=+-90.
    # Verified against astropy.wcs as ground truth, not just self-
    # consistency, since a wrong-but-self-consistent formula would still
    # pass a same-vs-same comparison.
    pixel_scale_arcsec = 1.72
    center_ra_deg, center_dec_deg = 30.0, 89.3
    w = _wcs_matching_this_projects_own_pixel_convention(center_ra_deg, center_dec_deg, pixel_scale_arcsec / 3600.0, 20.0)
    crpix_x, crpix_y = w.wcs.crpix
    cd11, cd12 = w.wcs.cd[0]
    extracted_rotation_deg = math.degrees(math.atan2(cd12, cd11))
    extracted_scale_arcsec = math.sqrt(cd11 ** 2 + w.wcs.cd[1][0] ** 2) * 3600.0

    px, py = w.all_world2pix([[0.0, 90.0]], 1)[0]
    expected = (px - crpix_x, py - crpix_y)

    for ra_deg in (0.0, 123.4, 250.0):
        delta_col, delta_row = project_radec_to_pixel(
            ra_deg, 90.0, center_ra_deg, center_dec_deg, extracted_scale_arcsec, extracted_rotation_deg,
        )
        assert delta_col == pytest.approx(expected[0], abs=0.01)
        assert delta_row == pytest.approx(expected[1], abs=0.01)


def test_correction_triangle_az_leg_changes_only_azimuth_not_altitude():
    when = datetime(2026, 6, 15, 3, 0, 0, tzinfo=timezone.utc)
    lat_deg, lon_deg = 46.18, 6.14
    axis_ra_deg, axis_dec_deg = 10.0, 89.3

    az0, alt0 = equatorial_to_altaz(axis_ra_deg, axis_dec_deg, lat_deg, lon_deg, when)

    (az_ra, az_dec), (pole_ra, pole_dec) = correction_triangle_radec(
        axis_ra_deg, axis_dec_deg, lat_deg, lon_deg, when,
    )

    az1, alt1 = equatorial_to_altaz(az_ra, az_dec, lat_deg, lon_deg, when)
    target_az_deg = 0.0 if lat_deg >= 0 else 180.0
    # Altitude unchanged by a pure-azimuth correction...
    assert alt1 == pytest.approx(alt0, abs=1e-3)
    # ...and the azimuth error is now fully corrected.
    assert ((az1 - target_az_deg + 180.0) % 360.0) - 180.0 == pytest.approx(0.0, abs=1e-3)
    assert (pole_ra, pole_dec) == true_pole_radec(lat_deg)


def test_correction_triangle_is_idempotent_once_azimuth_is_already_corrected():
    # Once at the az-corrected point (already on the target azimuth,
    # unchanged altitude), running the same solve again should be a
    # near no-op -- it's already the fixed point Newton's iteration
    # converges to.
    when = datetime(2026, 6, 15, 3, 0, 0, tzinfo=timezone.utc)
    lat_deg, lon_deg = 46.18, 6.14
    (az_ra, az_dec), _pole = correction_triangle_radec(10.0, 89.3, lat_deg, lon_deg, when)
    (az_ra2, az_dec2), _pole2 = correction_triangle_radec(az_ra, az_dec, lat_deg, lon_deg, when)
    assert az_ra2 == pytest.approx(az_ra, abs=1e-4)
    assert az_dec2 == pytest.approx(az_dec, abs=1e-4)


@pytest.mark.parametrize("east_arcsec,north_arcsec", [(0.0, 0.0), (3.0, -2.0), (30.0, -20.0), (60.0, 45.0)])
def test_offset_radec_by_east_north_round_trips_through_tangent_plane_offset(east_arcsec, north_arcsec):
    # offset_radec_by_east_north is the flat/small-angle inverse of
    # tangent_plane_offset_arcsec -- applying an (east, north) offset and
    # then measuring it back with the (exact) forward function should
    # recover the same (east, north) to a tight tolerance at the offset
    # sizes this is actually used for: a single live-estimate refresh
    # tick's own star-field shift (a fraction of an arcmin at 5Hz, not a
    # whole re-solve-sized jump -- see axis_radec_from_frame_shift's own
    # docstring for why large single-shot offsets near the pole are a
    # fundamentally different, much less accurate, regime for this flat
    # approximation).
    center_ra_deg, center_dec_deg = 47.0, 88.0
    new_ra_deg, new_dec_deg = offset_radec_by_east_north(center_ra_deg, center_dec_deg, east_arcsec, north_arcsec)
    measured_east, measured_north = tangent_plane_offset_arcsec(new_ra_deg, new_dec_deg, center_ra_deg, center_dec_deg)
    assert measured_east == pytest.approx(east_arcsec, abs=0.4)
    assert measured_north == pytest.approx(north_arcsec, abs=0.4)


@pytest.mark.parametrize("flip_parity", [False, True])
def test_axis_radec_from_frame_shift_tracks_axis_through_many_small_incremental_ticks(flip_parity):
    # axis_radec_from_frame_shift is meant to be called every ~200ms
    # (AlignmentPanel's own preview-refresh cadence) against the
    # IMMEDIATELY PREVIOUS live frame, accumulating many small updates
    # while the operator slowly turns the alt/az adjusters -- not fed one
    # big single-shot rotation. This mirrors that real usage: apply a
    # realistic *total* rotation (comparable to an actual PAA fine-tuning
    # adjustment) split over many small ticks, re-deriving each tick's
    # pixel shift from the true simulated rotation and feeding it through
    # axis_radec_from_frame_shift exactly as AlignmentPanel would, then
    # checking the accumulated estimate still tracks the true axis
    # closely. (A single large one-shot call, by contrast, is a
    # fundamentally less accurate regime for this flat local
    # approximation -- see the module's own docstring -- which is why
    # the plan pairs this with a manual "Re-solve" against a real plate
    # solve rather than trusting the live estimate indefinitely.)
    pixel_scale_arcsec = 1.68
    rotation_deg = -12.3
    axis_ra0, axis_dec0 = 47.0, 88.0
    center_ra0, center_dec0 = 47.3, 87.85  # a nearby but distinct reference-frame centre, as in a real PAA session

    rot_axis = np.array([0.4, -0.5, 0.3])
    total_angle_deg = 0.25  # 15', a realistic PAA fine-tuning adjustment
    n_ticks = 60

    true_axis_ra, true_axis_dec = axis_ra0, axis_dec0
    true_center_ra, true_center_dec = center_ra0, center_dec0
    est_axis_ra, est_axis_dec = axis_ra0, axis_dec0
    prev_center_ra, prev_center_dec = center_ra0, center_dec0

    for _ in range(n_ticks):
        R = _rotation_matrix(rot_axis, total_angle_deg / n_ticks)
        true_axis_ra, true_axis_dec = _to_radec(R @ _unit_vector(true_axis_ra, true_axis_dec))
        true_center_ra, true_center_dec = _to_radec(R @ _unit_vector(true_center_ra, true_center_dec))

        delta_col, delta_row = project_radec_to_pixel(
            prev_center_ra, prev_center_dec, true_center_ra, true_center_dec, pixel_scale_arcsec, rotation_deg, flip_parity,
        )
        est_axis_ra, est_axis_dec = axis_radec_from_frame_shift(
            est_axis_ra, est_axis_dec, delta_col, delta_row, pixel_scale_arcsec, rotation_deg, flip_parity,
        )
        prev_center_ra, prev_center_dec = true_center_ra, true_center_dec

    assert angular_separation_deg(est_axis_ra, est_axis_dec, true_axis_ra, true_axis_dec) * 3600.0 < 5.0


def test_axis_radec_from_frame_shift_is_a_no_op_for_zero_shift():
    axis_ra, axis_dec = axis_radec_from_frame_shift(47.0, 88.0, 0.0, 0.0, 1.68, -12.3, flip_parity=True)
    assert axis_ra == pytest.approx(47.0, abs=1e-9)
    assert axis_dec == pytest.approx(88.0, abs=1e-9)
